-- ============================================================
-- clinic.sql - Skema e Databazës (3NF)
-- Klinika Mjekësore - PW2526
-- ============================================================

-- TODO: CREATE DATABASE clinic_db CHARACTER SET utf8mb4;
-- TODO: USE clinic_db;

-- TODO: CREATE TABLE users (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   name VARCHAR(100) NOT NULL,
--   email VARCHAR(150) NOT NULL UNIQUE,
--   password_hash VARCHAR(255) NULL,          -- NULL nëse llogari Google
--   role ENUM('patient','doctor','admin') NOT NULL,
--   phone VARCHAR(20) NULL,
--   is_active TINYINT(1) DEFAULT 1,
--   google_id VARCHAR(100) NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   -- Kolona vetëm për mjekun (NULL për pacient/admin):
--   specialization VARCHAR(100) NULL,
--   bio TEXT NULL,
--   photo_path VARCHAR(255) NULL,
--   consultation_fee DECIMAL(8,2) NULL,
--   -- Kolona vetëm për pacientin (NULL për mjek/admin):
--   date_of_birth DATE NULL,
--   blood_type VARCHAR(5) NULL,
--   address VARCHAR(255) NULL,
--   emergency_contact VARCHAR(100) NULL
-- );

-- TODO: CREATE TABLE services (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   name VARCHAR(100) NOT NULL,
--   description TEXT NULL,
--   category VARCHAR(50) NOT NULL,
--   price DECIMAL(8,2) NOT NULL,
--   icon VARCHAR(50) NULL,
--   is_active TINYINT(1) DEFAULT 1
-- );

-- TODO: CREATE TABLE appointments (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   patient_id INT NOT NULL,
--   doctor_id INT NOT NULL,
--   service_id INT NOT NULL,
--   appointment_date DATE NOT NULL,
--   time_slot TIME NOT NULL,
--   status ENUM('pending','confirmed','completed','cancelled') DEFAULT 'pending',
--   notes TEXT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   FOREIGN KEY (patient_id) REFERENCES users(id) ON DELETE CASCADE,
--   FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE,
--   FOREIGN KEY (service_id) REFERENCES services(id)
-- );

-- TODO: CREATE TABLE prescriptions (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   appointment_id INT NOT NULL,
--   doctor_id INT NOT NULL,
--   patient_id INT NOT NULL,
--   file_path VARCHAR(255) NOT NULL,
--   uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   FOREIGN KEY (appointment_id) REFERENCES appointments(id),
--   FOREIGN KEY (doctor_id) REFERENCES users(id),
--   FOREIGN KEY (patient_id) REFERENCES users(id)
-- );

-- TODO: CREATE TABLE schedules (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   doctor_id INT NOT NULL,
--   day_of_week ENUM('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'),
--   start_time TIME NOT NULL,
--   end_time TIME NOT NULL,
--   is_available TINYINT(1) DEFAULT 1,
--   FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE
-- );

-- TODO: CREATE TABLE contact_queries (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   name VARCHAR(100) NOT NULL,
--   email VARCHAR(150) NOT NULL,
--   subject VARCHAR(200) NOT NULL,
--   message TEXT NOT NULL,
--   status ENUM('unread','read','resolved') DEFAULT 'unread',
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- TODO: CREATE TABLE session_logs (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   user_id INT NOT NULL,
--   role VARCHAR(20) NOT NULL,
--   action ENUM('login','logout') NOT NULL,
--   ip_address VARCHAR(45) NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
-- );

-- ============================================================
-- TODO: INSERT demo data:
-- Admin: admin@klinika.al / Admin@123
-- Mjek:  doktor@klinika.al / Doctor@123
-- Pacient: pacient@klinika.al / Patient@123
-- Shërbime: Kardiologji, Neurologji, Pediatri, Ortopedi,
--           Dermatologji, Laborator, Radiologji, etj.
-- ============================================================
